services:
  backend:
    build: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build: frontend
    depends_on:
      - backend
    environment:
      - API_URL: "http://localhost:8051/lca-arrivals"
    ports:
      - "8050:8050"
    restart: unless-stopped