services:
  backend:
    build: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8051 --reload
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: api-lca.costa365.site
      PORT: 8051
      VIRTUAL_PORT: 8051
    networks:
      - nginx-proxy

  frontend:
    build: 
      context: frontend
      args:
        VITE_API_URL: https://api-lca.costa365.site
    depends_on:
      - backend
    ports:
      - "8050:8050"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: lca.costa365.site
      PORT: 8050
      VIRTUAL_PORT: 8050
      NODE_ENV: production
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
