services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped