services:
  backend:
    build: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8051 --reload
    restart: unless-stopped

  frontend:
    build: 
      context: frontend
      args:
        VITE_API_URL: http://localhost:8051
    depends_on:
      - backend
    ports:
      - "8050:8050"
    restart: unless-stopped