services:
  backend:
    build: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8051 --reload
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8050:8050"
    environment:
      - VITE_API_URL=http://localhost:8051
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8050"
    depends_on:
      - backend
    restart: unless-stopped